name: nar2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.17.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py310hff52083_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.3=h5eee18b_3
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - platformdirs=3.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py310h5eee18b_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - python=3.10.8=haa1d7c7_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pyzmq=25.1.0=py310h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py310h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.40.0=h5082296_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py310h5764c6d_3
  - traitlets=5.13.0=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - wcwidth=0.2.9=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.3.0
    - accelerate==0.30.1
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - alignment-handbook==0.4.0.dev0
    - annotated-types==0.7.0
    - anyio==4.4.0
    - async-timeout==4.0.2
    - backoff==2.2.1
    - bitsandbytes==0.43.1
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - chex==0.1.5
    - click==8.1.7
    - datasets==2.19.1
    - deepspeed==0.12.2
    - dill==0.3.8
    - distro==1.9.0
    - dm-tree==0.1.7
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - einops==0.8.0
    - et-xmlfile==1.1.0
    - evaluate==0.4.0
    - filelock==3.13.1
    - flash-attn==2.5.8
    - frozenlist==1.3.3
    - fsspec==2023.12.2
    - gitdb==4.0.11
    - gitpython==3.1.43
    - h11==0.14.0
    - hf-transfer==0.1.6
    - hjson==3.1.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.23.0
    - importlib-resources==6.1.1
    - ipywidgets==8.1.1
    - jax==0.3.25
    - jaxlib==0.3.25
    - jinja2==3.1.2
    - joblib==1.4.2
    - jupyterlab-widgets==3.0.9
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.16
    - networkx==3.2.1
    - ninja==1.11.1.1
    - numpy==1.24.3
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.18.1
    - nvidia-nvjitlink-cu12==12.3.101
    - nvidia-nvtx-cu12==12.1.105
    - oauthlib==3.2.2
    - openai==1.31.0
    - openpyxl==3.1.3
    - opt-einsum==3.3.0
    - pandas==2.0.3
    - peft==0.11.1
    - pip==23.3.2
    - protobuf==3.20.2
    - py-cpuinfo==9.0.0
    - pyarrow==16.1.0
    - pyarrow-hotfix==0.6
    - pydantic==2.7.1
    - pydantic-core==2.18.2
    - pynvml==11.5.0
    - pytz==2024.1
    - pyyaml==6.0.1
    - regex==2023.12.25
    - responses==0.18.0
    - rich==13.7.1
    - safetensors==0.4.1
    - scikit-learn==1.5.0
    - scipy==1.9.3
    - sentencepiece==0.2.0
    - sentry-sdk==2.3.1
    - setproctitle==1.3.3
    - shtab==1.7.1
    - smmap==5.0.1
    - sniffio==1.3.1
    - sympy==1.12
    - threadpoolctl==3.5.0
    - tiktoken==0.7.0
    - tokenizers==0.15.0
    - toolz==0.12.0
    - torch==2.1.2
    - tqdm==4.65.0
    - transformers==4.41.1
    - tree-of-thoughts-llm==0.1.0
    - triton==2.1.0
    - trl==0.8.6
    - typing-extensions==4.4.0
    - tyro==0.8.4
    - tzdata==2024.1
    - urllib3==2.0.2
    - wandb==0.17.0
    - widgetsnbextension==4.0.9
    - xxhash==3.4.1
    - yarl==1.9.2
prefix: /home/ataylor2/anaconda3/envs/nar2
